### ISSUE TITLE
looking for example of how to use this lib

### ISSUE THREAD

**Issue by geib** [processone/yconf#1]
I am looking for a library to support using yaml config files for erlang releases, etc.
The tests look interesting, but I am wondering if there is an example of how to use this library
from an application. Also, is there a way to provide a schema, or is all validation done in the application.?

**Comment by prefiks** [comment]
Hello,

I know only about only user of this, and that will be ejabberd, you can check econf.erl and ejabberd_options.erl for most parts that are using it.

Validation is performed based on rules that you pass to yconf:parser/2, there is no way to load those rules from some special syntax file. Generally you will do something like this:

```
yconf:parse("/home/me/conf.yml", #{
  host => yconf:string(),
  opts => yconf:options(#{
    addr => yconf:ip(),
    count => yconf:non_neg_int()
  }
)}).
```
that when feed with:
```
host: "test.com"
opts:
  addr: "127.0.0.1"
  count: 100
```
should produce:
```
{ok,[{host,"test.com"},{opts,[{addr,{127,0,0,1}},{count,100}]}]}
```
